@url = http://localhost:4849

###
GET {{url}}/posts/user
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwicGhvbmUiOiIrOTk4OTA1Nzg5MjA0Iiwicm9sZSI6InBhc3NlbmdlciIsImlhdCI6MTY5NzEzNjI3OCwiZXhwIjoxNjk3NzQxMDc4fQ.322lb5JBEV92Mhh9XVX3eUF-TTUlEqLHa1f8UhfImoE

###
{
    "author_id": 7,
    "from_loc": "Xorazm Urganch",
    "to_loc": "Sirdaryo Mirobod",
    "go_time": "12.03.2023 12:00",
    "count": 3,
    "addition": ""
}

###
GET {{url}}/posts/

###

GET {{url}}/users
X-Access-Key: jnalndlanflasn;flrinioe903409hf0

###

POST http://31.129.110.72:4849/users/register
Content-Type: application/json

{
    "name": "Saad Takhir",
    "phone": "+998905789204",
    "password": "Saad9204",
    "role": "passenger"
}

###



POST http://31.129.110.72:4849/users/login
Content-Type: application/json


{
    "phone": "+998905789204",
    "password": "Saad9204"
}
###

PM2           | App [hamroh-api:1] exited with code [0] via signal [SIGINT]
PM2           | App [hamroh-api:1] starting in -fork mode-
PM2           | App [hamroh-api:1] online
1|hamroh-api  | src/server.ts(10,13): error TS2349: This expression is not callable.
1|hamroh-api  |   Type 'typeof e' has no call signatures.
1|hamroh-api  | src/server.ts(12,9): error TS2349: This expression is not callable.
1|hamroh-api  |   Type '{ default: <T extends CorsRequest = CorsRequest>(options?: CorsOptions | CorsOptionsDelegate<T> | undefined) => (req: T, res: { ...; }, next: (err?: any) => any) => void; }' has no call signatures."

###

GET {{url}}/users/verify
X-Auth-Key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwicGhvbmUiOiIrOTk4OTA1Nzg5MjA0Iiwicm9sZSI6InBhc3NlbmdlciIsImlhdCI6MTY5Njc2NzA3MSwiZXhwIjoxNjk3MzcxODcxfQ.OGOJk0_6WUXb8oRmRDSMSJgXfmNzahNkR8HKsSVzAyc

###

| App [hamroh-api:1] exited with code [0] via signal [SIGINT]
PM2           | App [hamroh-api:1] starting in -fork mode-
PM2           | App [hamroh-api:1] online
1|hamroh-api  | src/server.ts(10,13): error TS2349: This expression is not callable.
1|hamroh-api  |   Type 'typeof e' has no call signatures.
1|hamroh-api  | src/server.ts(12,9): error TS2349: This expression is not callable.
1|hamroh-api  |   Type '{ default: <T extends CorsRequest = CorsRequest>(options?: CorsOptions | CorsOptionsDelegate<T> | undefined) => (req: T, res: { ...; }, next: (err?: any) => any) => void; }' has no call signatures.